<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<title>404 Not Found</title>
	
	<link rel="stylesheet" href="/assets/error/404.css" />
</head>

<body>

<div id="wrap">
	<div id="inner">
		<h1>404 页面存在感丢失</h1>
		<p>没有找到要访问的文件，可以选择：
			<ul>
				<li><a href="https://bbs2.kdays.net/">去讨论版</a></li>
				<li><a href="/">返回首页</a></li> 
				<div style="clear: both;"></div>
			</ul>
		</p>
	</div>
</div>

</body></html>