<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="UTF-8">
        <title>KDays - GalGame综合向交流站点</title>

        <meta name="keywords" content="kdays,galgame,gal汉化,kdays汉化组" />
        <meta name="description" content="KDays是一个正在努力创建属于自己氛围的ACG站点，目前致力于GalGame汉化等多个领域" />

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"/>
        <link rel="stylesheet" href="/assets/home.css">
    </head>

    <body>
        <div class="main-center web-home">
            <div class="site-logo" aria-label="KDays Logo"></div>
            <div class="header-bar">
                <nav>
                    <ul class="nav-list">
                        <li>
                            <a class="nav-block" href="https://bbs2.kdays.net/">
                                <i class="fa-regular fa-comments fa-3x" style="margin-bottom:16px;color:#0078d7;"></i>
                                <div class="nav-block-text">
                                    <div class="nav-title">论坛</div>
                                    <div class="nav-desc">交流/讨论</div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a class="nav-block" href="https://wk.kdays.net/">
                                <i class="fa-solid fa-book fa-3x" style="margin-bottom:16px;color:#43a047;"></i>
                                <div class="nav-block-text">
                                    <div class="nav-title">萌文库</div>
                                    <div class="nav-desc">轻小说</div>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a class="nav-block" href="https://gdb.kdays.net/">
                                <i class="fa-solid fa-gamepad fa-3x" style="margin-bottom:16px;color:#ff9800;"></i>
                                <div class="nav-block-text">
                                    <div class="nav-title">ACGLife</div>
                                    <div class="nav-desc">GalGame 数据库</div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>

        <footer>

            <p>
                <a href="/about/">关于我们</a> 
                <a target="_blank" href="https://docs.kdays.work/docs/">API文档</a>

                <a target="_blank" href="https://status.kdays.net/">服务状态</a>
            </p>
            <small>© 2008 - <?=date('Y')?> Project Chobits, KDays Team</small>
        </footer>


        <div class="page-bg-bottom"></div>
    </body>
</html>


        <script>
            if (document.domain == "kdays.cn" || document.domain == "www.kdays.cn") {  
                location.href = 'http://kdays.net/'; 
            }
        </script>	