<?php include("_header.phtml"); ?>

<div class="about-body-center">
    <h3>日常渠道</h3>
    <p>站点方面的问题或者BUG申报，可前往<a href="https://bbs.kdays.net/thread/22">论坛的站务管理</a>板块进行申报</p>

    <h3>如不方便使用论坛，可以通过如下方式联系站长</h3>
    <ul>
        <li>邮箱: admin@kdays.net</li>
    </ul>

    <h3>相关交流群</h3>
    <ul>
        <li>QQ群: 1140944 （加群说明原因）</li>
        <li>Telegram: <a href="https://t.me/joinchat/RU_uIzx1l782ZjZl">KDays会员电报群</a></li>
    </ul>

    <p>If you need to send a copyright notice (like DMCA), please contact us via email at admin@kdays.net</p>
</div>

<?php include("_footer.phtml"); ?>
